# Generated by Django 4.2.3 on 2023-07-13 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_courses_image_alter_courses_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
