# Generated by Django 4.2.3 on 2023-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_courses_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
        ),
    ]
