# Generated by Django 4.2.3 on 2023-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='enrollments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='instructors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='learners',
            field=models.IntegerField(default=0),
        ),
    ]
