# Generated by Django 4.2.3 on 2023-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_about_courses_about_enrollments_about_instructors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
