# Generated by Django 4.2.3 on 2023-07-26 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_courses_lecture_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='rating',
        ),
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
