# Generated by Django 4.2.3 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_courses_rating_courses_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='is_pro',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
