# Generated by Django 4.2.3 on 2023-07-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_courses_is_pro_user_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
